# Generated by Django 5.1.1 on 2024-10-15 20:06

import datetime
import django.contrib.auth.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pfp', models.ImageField(choices=[('bear.png', 'Bear'), ('bird.png', 'Bird'), ('chameleon.png', 'Chameleon'), ('frog.png', 'Frog'), ('raccoon.png', 'Raccoon'), ('turtle.png', 'Turtle')], default='bear.png', upload_to='profile_pictures/')),
                ('profilename', models.CharField(default='John Doe', max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Non-Binary/Other', 'Non-Binary/Other'), ('Female', 'Female')], default='Male', max_length=16)),
                ('age', models.CharField(choices=[('61+', '61+'), ('31-40', '31-40'), ('18-20', '18-20'), ('51-60', '51-60'), ('21-30', '21-30'), ('41-50', '41-50'), ('Under 15', 'Under 15'), ('15-17', '15-17')], default='21-30', max_length=8)),
                ('address1', models.CharField(default='123 Main Street', max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('WY', 'WY'), ('KS', 'KS'), ('SD', 'SD'), ('MT', 'MT'), ('ME', 'ME'), ('CO', 'CO'), ('IL', 'IL'), ('MI', 'MI'), ('VA', 'VA'), ('MS', 'MS'), ('WI', 'WI'), ('AK', 'AK'), ('TN', 'TN'), ('DE', 'DE'), ('IN', 'IN'), ('CA', 'CA'), ('SC', 'SC'), ('AR', 'AR'), ('NY', 'NY'), ('ID', 'ID'), ('ND', 'ND'), ('MN', 'MN'), ('MO', 'MO'), ('NC', 'NC'), ('NV', 'NV'), ('VT', 'VT'), ('OK', 'OK'), ('PA', 'PA'), ('UT', 'UT'), ('TX', 'TX'), ('GA', 'GA'), ('MA', 'MA'), ('NM', 'NM'), ('OH', 'OH'), ('RI', 'RI'), ('WA', 'WA'), ('CT', 'CT'), ('HI', 'HI'), ('IA', 'IA'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('WV', 'WV'), ('OR', 'OR'), ('AL', 'AL'), ('LA', 'LA'), ('MD', 'MD'), ('FL', 'FL'), ('KY', 'KY'), ('AZ', 'AZ')], default='AL', max_length=2)),
                ('city', models.CharField(default='Huntsville', max_length=100)),
                ('zipcode', models.CharField(default='12345', max_length=9)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('skills', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('notififications', models.TextField(blank=True)),
                ('availability', models.JSONField(default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('Urgent', 'urgent'), ('Not urgent', 'not_urgent'), ('Very urgent', 'very_urgent')], default='Not urgent', max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('volunteers', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
