# Generated by Django 5.1.1 on 2024-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('Not urgent', 'not_urgent'), ('Urgent', 'urgent'), ('Very urgent', 'very_urgent')], default='Not urgent', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('31-40', '31-40'), ('51-60', '51-60'), ('Under 15', 'under_15'), ('15-17', '15-17'), ('21-30', '21-30'), ('41-50', '41-50'), ('18-20', '18-20'), ('61+', '61+')], default='21-30', max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Non-binary/Other', 'non_binary_other'), ('Male', 'male')], default='Male', max_length=16),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('UT', 'UT'), ('HI', 'HI'), ('OK', 'OK'), ('WA', 'WA'), ('MT', 'MT'), ('NH', 'NH'), ('ID', 'ID'), ('NV', 'NV'), ('VA', 'VA'), ('CT', 'CT'), ('AZ', 'AZ'), ('NJ', 'NJ'), ('VT', 'VT'), ('GA', 'GA'), ('NE', 'NE'), ('WY', 'WY'), ('KY', 'KY'), ('IL', 'IL'), ('DE', 'DE'), ('WV', 'WV'), ('AR', 'AR'), ('ND', 'ND'), ('IA', 'IA'), ('KS', 'KS'), ('MA', 'MA'), ('MN', 'MN'), ('MO', 'MO'), ('TN', 'TN'), ('LA', 'LA'), ('CA', 'CA'), ('MI', 'MI'), ('TX', 'TX'), ('WI', 'WI'), ('RI', 'RI'), ('OR', 'OR'), ('NM', 'NM'), ('AK', 'AK'), ('SD', 'SD'), ('AL', 'AL'), ('NY', 'NY'), ('ME', 'ME'), ('OH', 'OH'), ('FL', 'FL'), ('PA', 'PA'), ('MS', 'MS'), ('IN', 'IN'), ('MD', 'MD'), ('SC', 'SC'), ('CO', 'CO'), ('NC', 'NC')], default='AL', max_length=2),
        ),
    ]
