# Generated by Django 5.1.1 on 2024-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("Not urgent", "not_urgent"),
                    ("Very urgent", "very_urgent"),
                    ("Urgent", "urgent"),
                ],
                default="Not urgent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="age",
            field=models.CharField(
                choices=[
                    ("21-30", "21-30"),
                    ("Under 15", "under_15"),
                    ("41-50", "41-50"),
                    ("31-40", "31-40"),
                    ("15-17", "15-17"),
                    ("51-60", "51-60"),
                    ("18-20", "18-20"),
                    ("61+", "61+"),
                ],
                default="21-30",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Female", "female"),
                    ("Non-binary/Other", "non_binary_other"),
                    ("Male", "male"),
                ],
                default="Male",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="pfp",
            field=models.ImageField(
                choices=[
                    ("profile_pictures/bear.png", "bear"),
                    ("profile_pictures/bird.png", "bird"),
                    ("profile_pictures/chameleon.png", "chameleon"),
                    ("profile_pictures/frog.png", "frog"),
                    ("profile_pictures/raccoon.png", "raccoon"),
                    ("profile_pictures/turtle.png", "turtle"),
                ],
                default="profile_pictures/bear.png",
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="state",
            field=models.CharField(
                choices=[
                    ("WI", "WI"),
                    ("OH", "OH"),
                    ("WA", "WA"),
                    ("MN", "MN"),
                    ("PA", "PA"),
                    ("HI", "HI"),
                    ("MI", "MI"),
                    ("VA", "VA"),
                    ("KS", "KS"),
                    ("ND", "ND"),
                    ("IA", "IA"),
                    ("AZ", "AZ"),
                    ("RI", "RI"),
                    ("WV", "WV"),
                    ("CO", "CO"),
                    ("MD", "MD"),
                    ("NY", "NY"),
                    ("NJ", "NJ"),
                    ("TN", "TN"),
                    ("TX", "TX"),
                    ("UT", "UT"),
                    ("NM", "NM"),
                    ("MT", "MT"),
                    ("MA", "MA"),
                    ("MS", "MS"),
                    ("FL", "FL"),
                    ("ID", "ID"),
                    ("NV", "NV"),
                    ("OK", "OK"),
                    ("AR", "AR"),
                    ("MO", "MO"),
                    ("NH", "NH"),
                    ("IN", "IN"),
                    ("VT", "VT"),
                    ("CT", "CT"),
                    ("AK", "AK"),
                    ("OR", "OR"),
                    ("ME", "ME"),
                    ("AL", "AL"),
                    ("DE", "DE"),
                    ("NC", "NC"),
                    ("IL", "IL"),
                    ("CA", "CA"),
                    ("LA", "LA"),
                    ("SD", "SD"),
                    ("KY", "KY"),
                    ("GA", "GA"),
                    ("NE", "NE"),
                    ("SC", "SC"),
                    ("WY", "WY"),
                ],
                default="AL",
                max_length=2,
            ),
        ),
    ]
