# Generated by Django 5.1.1 on 2024-09-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('Not urgent', 'not_urgent'), ('Very urgent', 'very_urgent'), ('Urgent', 'urgent')], default='Not urgent', max_length=20),
        ),
    ]
