# Generated by Django 5.1.1 on 2024-10-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_urgency_alter_volunteer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('15-17', '15-17'), ('51-60', '51-60'), ('Under 15', 'under_15'), ('41-50', '41-50'), ('18-20', '18-20'), ('21-30', '21-30'), ('61+', '61+'), ('31-40', '31-40')], default='21-30', max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Non-binary/Other', 'non_binary_other'), ('Male', 'male'), ('Female', 'female')], default='Male', max_length=16),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('IL', 'IL'), ('SC', 'SC'), ('SD', 'SD'), ('MI', 'MI'), ('LA', 'LA'), ('CT', 'CT'), ('TX', 'TX'), ('AK', 'AK'), ('OH', 'OH'), ('IA', 'IA'), ('ND', 'ND'), ('AZ', 'AZ'), ('ME', 'ME'), ('MO', 'MO'), ('UT', 'UT'), ('OK', 'OK'), ('NE', 'NE'), ('TN', 'TN'), ('MT', 'MT'), ('KY', 'KY'), ('NM', 'NM'), ('WI', 'WI'), ('MD', 'MD'), ('NY', 'NY'), ('WY', 'WY'), ('CO', 'CO'), ('GA', 'GA'), ('RI', 'RI'), ('NV', 'NV'), ('DE', 'DE'), ('OR', 'OR'), ('PA', 'PA'), ('AR', 'AR'), ('MS', 'MS'), ('NH', 'NH'), ('FL', 'FL'), ('NC', 'NC'), ('IN', 'IN'), ('MA', 'MA'), ('ID', 'ID'), ('VT', 'VT'), ('VA', 'VA'), ('CA', 'CA'), ('KS', 'KS'), ('NJ', 'NJ'), ('AL', 'AL'), ('MN', 'MN'), ('WA', 'WA'), ('HI', 'HI'), ('WV', 'WV')], default='AL', max_length=2),
        ),
    ]
