# Generated by Django 5.1.1 on 2024-10-13 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_volunteer_age_alter_volunteer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='urgency',
            field=models.CharField(choices=[('Not urgent', 'not_urgent'), ('Very urgent', 'very_urgent'), ('Urgent', 'urgent')], default='Not urgent', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('18-20', '18-20'), ('61+', '61+'), ('51-60', '51-60'), ('15-17', '15-17'), ('31-40', '31-40'), ('Under 15', 'under_15'), ('21-30', '21-30'), ('41-50', '41-50')], default='21-30', max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Non-binary/Other', 'non_binary_other'), ('Male', 'male')], default='Male', max_length=16),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(choices=[('SD', 'SD'), ('IN', 'IN'), ('OR', 'OR'), ('RI', 'RI'), ('CA', 'CA'), ('AZ', 'AZ'), ('MD', 'MD'), ('HI', 'HI'), ('SC', 'SC'), ('MT', 'MT'), ('WY', 'WY'), ('VT', 'VT'), ('VA', 'VA'), ('KY', 'KY'), ('MS', 'MS'), ('AL', 'AL'), ('MN', 'MN'), ('UT', 'UT'), ('ND', 'ND'), ('MA', 'MA'), ('ME', 'ME'), ('CT', 'CT'), ('GA', 'GA'), ('NE', 'NE'), ('NH', 'NH'), ('WA', 'WA'), ('NM', 'NM'), ('MI', 'MI'), ('OH', 'OH'), ('AK', 'AK'), ('AR', 'AR'), ('NV', 'NV'), ('CO', 'CO'), ('KS', 'KS'), ('LA', 'LA'), ('NC', 'NC'), ('IL', 'IL'), ('NJ', 'NJ'), ('WV', 'WV'), ('TX', 'TX'), ('FL', 'FL'), ('OK', 'OK'), ('WI', 'WI'), ('NY', 'NY'), ('PA', 'PA'), ('DE', 'DE'), ('TN', 'TN'), ('ID', 'ID'), ('MO', 'MO'), ('IA', 'IA')], default='AL', max_length=2),
        ),
    ]
